echo "# huanban" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:huanban/huanban.git
git push -u origin main
git remote add origin git@github.com:huanban/huanban.git
git branch -M main
git push -u origin main
